eureka:
    client:
        service-url:
            defaultZone: http://eureka7001.com:7001/eureka/ #,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
    instance:
        instance-id: cloud-store-admin
        prefer-ip-address: true

info:
    app:
        name: jackzhan-cloud-store

#feign:
#    hystrix:
#        enabled: true

server:
    port: 9992
    session:
        store-dir: ./session #session序列化存储数据的目录
        persistent: true  #重新启动之间持续会话数据
    context-path: /admin

spring:
    application:
        name: cloud-store-admin

