eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/ #,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: cloud-store-member
    prefer-ip-address: true

info:
  app:
    name: jackzhan-cloud-store

mybatis-plus:
  mapper-locations: classpath:mybatis/mapper/**/*.xml
  type-aliases-package: club.jackzhan.cloudstore.entities
  # 原生配置
  configuration:
    interceptors: club.jackzhan.cloudstore.web.interceptor.PageInterceptor
  global-config:
    #驼峰下划线转换
    db-column-underline: true
    #刷新mapper 调试神器
    refresh-mapper: true

server:
  port: 9991
  tomcat:
    uri-encoding: UTF-8
  context-path: /

spring:
  application:
    name: cloud-store-member
  datasource:
    url: jdbc:mysql://localhost:3306/cloud-store-member?useUnicode=true&characterEncoding=utf-8
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: admin
  http:
    encoding:
      force: true
      charset: utf-8
      enabled: true

logging:
  level:
    club:
      jackzhan:
        cloudstore:
          mapper:
            debug
